### ISSUE TITLE
"ERROR: [youtube:tab] WL: YouTube said: The playlist does not exist."

### ISSUE THREAD

**Issue by Joshfindit** [Jeeaaasus/youtube-dl#67]
I tried using `:latest` and `:unstable`, but both give the same error.

Snip of `docker-compose.yml`:

```yaml
    container_name: yt-dlp
    image: jeeaaasustest/youtube-dl:unstable
    environment:
      PUID: 1000
      PGID: 50
      youtubedl_lockfile: 'true'
      youtubedl_cookies: 'true'
      youtubedl_quality: '720'
      youtubedl_watchlater: 'true'
```

`ls -la yt-dlp/` *(Mapped to `/config/`)*
```
-rw-r--r-- 1 josh staff  830 Dec 31 14:21 args.conf
-rw-r--r-- 1 josh staff  455 Dec 31 14:21 channels.txt
-rw-r--r-- 1 josh staff  482 Dec 31 14:30 cookies.txt
```

`args.conf` and `channels.txt` are unmodified, and `cookies.txt` works with the `vimagick/youtube-dl` container.
