### ISSUE TITLE
Help with permission error

### ISSUE THREAD

**Issue by hbdsklf** [Jeeaaasus/youtube-dl#99]
When I add a new channel it downloads as expected. However, if a channel has a new video I get an error like the following (the tmpfile filename is obviously different each time, video ID redacted):

```
[download] Downloading item 16 of 16
[youtube] Extracting URL: https://www.youtube.com/watch?v=xxxxxxx
[youtube] Sleeping 1.0 seconds ...
[youtube] xxxxxxx: Downloading webpage
[youtube] Sleeping 1.0 seconds ...
[youtube] xxxxxxx: Downloading ios player API JSON
[youtube] Sleeping 1.0 seconds ...
[youtube] xxxxxxx: Downloading mweb player API JSON
[youtube] Sleeping 1.0 seconds ...
[youtube] xxxxxxx: Downloading m3u8 information
[info] xxxxxxx: Downloading subtitles: en-GB
[SponsorBlock] Fetching SponsorBlock segments
[SponsorBlock] Found 3 segments in the SponsorBlock database
[info] Testing format 616
ERROR: [Errno 13] Permission denied: './tmp8a9m5ixc.tmp'
```

I tried setting PUID and PGID to 1000 (my user's PID/GID) and 0 (as I read in another issue this could help). I'm not sure if this worked, because on startup it always logs the following regardless:

```
UID/GID
---------------------------------------
User uid:  911
User gid:  911
---------------------------------------
```

I'm starting the container using the following docker compose file (there are other services defined in the same file):

```
services:
  yt:
    image: jeeaaasustest/youtube-dl
    container_name: youtube-dl
    volumes:
      - somedir/config:/config
      - somedir/media:/downloads
    environment:
      TZ: Europe/Zurich
      youtubedl_webui: true
      PUID: 0
      PGID: 0
    ports:
      - 5000:8080
    restart: always
```

I guess I'm missing something obvious. Any help would be appreciated!

**Comment by Jeeaaasus** [comment]
Hello there, since the "UID/GID" print is not changing, the way you are not defining environment variables must not be working. I see that it should work, but personally I have always used this structure with dashes and equal signs:
```
services:
  yt:
    image: jeeaaasustest/youtube-dl
    container_name: youtube-dl
    volumes:
      - somedir/config:/config
      - somedir/media:/downloads
    environment:
      - TZ=Europe/Zurich
      - youtubedl_webui=true
      - PUID=0
      - PGID=0
    ports:
      - 5000:8080
    restart: always
```

Hopefully that works for you!
